export const WEB_API_BASE_URL = 'https://nhl-api-proxy.onrender.com/web/v1';
export const STATS_API_BASE_URL = 'https://nhl-api-proxy.onrender.com/stats/rest';
export const SEARCH_API_BASE_URL = 'https://search.d3.nhle.com/api/v1/search/player?culture=en-us';
export const ASSETS_BASE_URL = 'https://assets.nhle.com';

// This is a mapping of team abbreviations to their corresponding team IDs in the NHL API.
// The team IDs are used to fetch specific data for each team, such as rosters, stats, and other information.
export const teamAbbrevToIdMap: Record<string, number> = {
  QUE: 32,
  MTL: 8,
  TSP: 58,
  BUF: 7,
  OAK: 46,
  KCS: 48,
  SEN: 36,
  TBD: 70,
  ATL: 11,
  SLE: 45,
  WIN: 33,
  SJS: 28,
  QBD: 42,
  ARI: 53,
  FLA: 13,
  CAR: 12,
  WPG: 52,
  NSH: 18,
  PHX: 27,
  MWN: 41,
  QUA: 39,
  HAM: 37,
  DCG: 40,
  CLR: 35,
  PIR: 38,
  HFD: 34,
  NJD: 1,
  OTT: 9,
  COL: 21,
  NYA: 44,
  WSH: 15,
  MNS: 31,
  NHL: 99,
  MMR: 43,
  CLE: 49,
  BRK: 51,
  DFL: 50,
  CGS: 56,
  AFM: 47,
  TAN: 57,
  STL: 19,
  DET: 17,
  NYR: 3,
  ANA: 24,
  CHI: 16,
  SEA: 55,
  PIT: 5,
  BOS: 6,
  DAL: 25,
  TBL: 14,
  PHI: 4,
  MIN: 30,
  CBJ: 29,
  NYI: 2,
  VAN: 23,
  LAK: 26,
  UTA: 68,
  TOR: 10,
  EDM: 22,
  VGK: 54,
  CGY: 20
};
